imports
```{r}
# install.packages("randomForest")
# install.packages("xgboost")
# install.packages("caret")
# install.packages("gains")
#install.packages("rpart")
library(randomForest)
library(xgboost)
library(caret)
library(gains)
library(rpart)
```


```{r}
data <- read.csv("data/final_project_dataset.csv")

# colnames(data)
# typeof(data$maximum_sustained_wind_knots)
# typeof(data$maximum_pressure)

data <- subset(data,
             select = -c(name, X, index, record_identifier, year.x))

sorted_unique_values <- sort(unique(data$status_of_system))

sorted_unique_values


data$status_of_system <- gsub("HU", 1, data$status_of_system)
data$status_of_system <- gsub("TS", 0, data$status_of_system)
```

```{r}
set.seed(1) #mention that this should be normalized across our models
train_index <- sample(c(1:dim(data)[1]), dim(data)[1] * 0.6)
valid_index <- setdiff(c(1:dim(data)[1]), train_index)

train <- data[train_index, ]
valid <- data[valid_index, ]
head(train)
```

```{r}
mod <- rpart(status_of_system ~
               maximum_pressure + maximum_sustained_wind_knots + date,
             data = train,
             cp = 0.00001, minbucket = 100, maxdepth = 7)


options(scipen = 10)
printcp(mod)
```

```{r}
rp_train <- data.frame(maximum_sustained_wind_knots = train$maximum_sustained_wind_knots,
                        status_of_system = train$status_of_system,
                        anomaly = train$anomaly,
                        maximum_pressure = train$maximum_pressure)

rp_valid <- data.frame(
                        maximum_sustained_wind_knots = valid$maximum_sustained_wind_knots,
                        status_of_system = valid$status_of_system,
                        anomaly = valid$anomaly,
                        maximum_pressure = valid$maximum_pressure)


train_ctrl <- trainControl(method = "cv",
                           number = 10,
                           search = "grid")


model_cv_grid <- train(status_of_system ~ anomaly + maximum_pressure,
                       data = rp_train,
                       method = "rf",
                       metric = "Accuracy",
                       trControl = train_ctrl,
                       ntree = 741,
                       keep.forest = TRUE,
                       importance = TRUE)

model_cv_grid

```

```{r}
ypred <- predict(model_cv_grid, rp_valid)
ypred

# ypred <- factor(ypred, levels = levels(rp_valid$status_of_system))
true_labels <- factor(rp_valid$status_of_system, levels = levels(ypred))

cfm <- confusionMatrix(true_labels, ypred)

```

```{r}


```
